### ISSUE TITLE
Difference between chip2_instruct_alpha and  joi_instruct_alpha 

### ISSUE THREAD

**Issue by Keith-Hon** [Rallio67/language-model-agents#3]
Is chip2 for "clip" from openai? What are the full names of chip and joi?

**Comment by Rallio67** [comment]
They are just made up names to watermark the assistant.
The order of improvements goes:
Rosey v3 dataset
Chip v4 dataset
Joi v5 dataset
Chip2 v6 dataset

Each new model is with an improvement to the dataset. Either removing some lower quality things or adding some new things.

**Comment by Keith-Hon** [comment]
Thanks for the answer. Is there any documentation from Open Assistant that mentions these dataset differences?

**Comment by Rallio67** [comment]
No. The documentation on the front page of the repo is what you can look at if you would like to learn more about it.

Because these are experimental work in progress and changing a lot I am not spending too much time writing down lots of details about each version. When the datasets are completed there will be more documentation and you can find it on LAION (in addition to here). The main people with open assistant are not so interested in instruction tuning (last time I checked) and would rather train their models just on the "roleplaying" materials generated by people on their data collection site.

The purpose of the efforts here are to generate high quality natural instructions and response pairs that can be used to quickly "instruction tune" any large language model and give it some good performance.
