### ISSUE TITLE
Download and preprocess datasets

### ISSUE THREAD

**Issue by robinsongh381** [Rallio67/language-model-agents#4]
Thank you for shaing great works on both github and huggingface.

Do you have any plan to release and share how to download and preprocess the datasets for training ?

**Comment by Rallio67** [comment]
If you look on my github it has all the stuff you need to do this. Load the json using python or whichever json reader, and then print out the json so that it has the format you like for your chatbot. The example "rallio_test.txt" shows one example of how to do this.

The jsons are a list of tuples formatted with "(instruction,response)"
