### ISSUE TITLE
What is the difference between instruct_alpha and retrieval_alpha models ?

### ISSUE THREAD

**Issue by robinsongh381** [Rallio67/language-model-agents#5]
I found your models on huggingface and i was wondering what is the difference betwen [chip2_12B_instruct_alpha](https://huggingface.co/Rallio67/chip2_12B_instruct_alpha) and [chip2_12B_retrieval_alpha](https://huggingface.co/Rallio67/chip2_12B_retrieval_alpha) ?

Are they different in terms of training datasets ?

**Comment by Rallio67** [comment]
They are extremely similar. The only difference is that for the retrieval alpha the context used to generate the answer is put inside of special brackets

User: Here is my question

--[Article name: Article text related to the question]--

Chip2: Here is my answer using the text I looked up in the article.

Chip2 without retrieval doesn't include the article used to generate the answer. It works the same as all the other models I uploaded on HF. We are working on getting a good retrieval setup that is easily compatible with these datasets and will pbulish some more soon. Also on LAION.

**Comment by robinsongh381** [comment]
@Rallio67 thank you for reply. I have a further question based on your response.

Is the `retrieval_alpha` model pre-trained with the same manner - concat the external article with the user input ?

If this is the case, how did you prepare the training datasets for the `retrieval_alpha` model ?

If this is NOT the case, how `retrieval_alpha` model would be capable of leveraging external articles without being trained to do so during pre-training ?

Thank you

**Comment by Rallio67** [comment]
In building the datasets, one type of commonly used approach is to take a context from some source text and then generate some questions related to that source text. In general with instruction tuning, I just use the question / instruction for the training. For the retrieval alpha instead of a tuple of (instruction,response) I have a tuple that is (instruction, context, response) and then that example is included in the training in the same was as with rallio_test.txt

So if you now have some external information you want to the model to use in consideration of its answer, then you paste it in between the brackets --[paste it here]-- with that exact format shown below. So in practice to use this you need to stop generation at the bracket, retrieve whatever the relevant text is via some kind of database lookup, and then close the bracket and the agent will generate an answer incorporating (hopefully) the text in the bracket.

```
User: Here is my question

--[Article name: Article text related to the question]--

Chip2: Here is my answer using the text I looked up in the article.<|endoftext|>```
